### ISSUE TITLE
Error selenium [winerror 2]

### ISSUE THREAD

**Issue by dk2010** [mpfarmer/TwSearchEnabled#1]
Hi! I'm quite new to programming and i get the following error:
Could anyone please help to fix this :)?

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\nlkroe03\Python\lib\site-packages\selenium\webdriver\common\service.py", line 74, in start
    stdout=self.log_file, stderr=self.log_file)
  File "C:\Users\nlkroe03\Python\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\nlkroe03\Python\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nlkroe03\Python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\nlkroe03\Python\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/nlkroe03/Desktop/Afstuderen/python/Twitter old tweets/TwSearchEnabled-master/tweetsearch.py", line 39, in getTweet
    browser = webdriver.Firefox()
  File "C:\Users\nlkroe03\Python\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 144, in __init__
    self.service.start()
  File "C:\Users\nlkroe03\Python\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by mpfarmer** [comment]
@dk2010 
Can you refer to this issue, sorry didn't respond to you.
https://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path
